# Generated by Django 4.2.1 on 2023-05-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
